# -*- coding: utf-8 -*-
"""smlA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zr5GDP235T7Idh47cZvu2-bHlOb5Kx5U
"""

#KAUSHAL SANADHYA MT19133

import numpy as np
print("enter value of w1: ")
w1=(float(input()))

print("enter number of dimensions: ")
d=(float(input()))

print("enter the value of Std deviation: ")
sigma=(float(input()))

x=[]
print("enter X: ")
for i in range(int(d)):
  x.append(float(input()))

u=[]
print("enter u: ")
for i in range(int(d)):
  u.append(float(input()))


#x=np.array([1,1])
#u1=np.array([0.5,0.5])
x=np.array(x)
u=np.array(u)

x=np.transpose(x)
exp1=np.dot(u,x)
exp1=exp1/(sigma**2)
exp2=np.dot(u,np.transpose(u))
exp2=exp2/(2*(sigma**2))
val=np.log(w1) + exp1 -exp2 
print (val)

#KAUSHAL SANADHYA MT19133

import numpy as np
print("enter value of w2: ")
w2=(float(input()))

print("enter number of dimensions: ")
d=(float(input()))

print("enter the value of Std deviation: ")
sigma=(float(input()))

x=[]
print("enter X: ")
for i in range(int(d)):
  x.append(float(input()))

u=[]
print("enter u: ")
for i in range(int(d)):
  u.append(float(input()))


#x=np.array([1,1])
#u1=np.array([0.5,0.5])
x=np.array(x)
u=np.array(u)

x=np.transpose(x)
exp1=np.dot(u,x)
exp1=exp1/(sigma**2)
exp2=np.dot(u,np.transpose(u))
exp2=exp2/(2*(sigma**2))
val=np.log(w2) + exp1 -exp2 
print (val)