# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_XhOR2x0RvaV-fiwZGo_YLLUDpGmDLX4
"""

#KAUSHAL SANADHYA MT19133

import numpy as np
d = input("Enter number of dimensions: ") 
cov = [] 
mu=[]  
print("enter your cov matrix row by row: ")  
for i in range(int(d)):           
    temp =[] 
    for j in range(int(d)):
      temp.append(float(input())) 
    cov.append(temp) 
print("enter your mean vector: ")
for i in range(int(d)):
  mu.append(float(input()))

print("enter number of samples to be generated: ")
num=int(float(input()))

print(d)
print(cov)
print(mu)


normal = np.random.multivariate_normal(mu,cov, num)
print(normal)